### ISSUE TITLE
Refactor C++ to reduce memory footprint

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-paper#18]
As noted in #16, the C++ versions seem to use a lot of memory. We can refactor to either run one at a time, or try to free the memory in between the different versions. I was running out on a 32G machine.

@molpopgen - I suspect this might be the reason you were seeing the weird step change behaviour in timings from the C++ versions. A process holding that much memory is probably going to be using different malloc strategies/treated differently by the kernel.

What's the easiest thing to do here?

**Comment by molpopgen** [comment]
I'll refactor to run 1 at a time and return the result.  I have a 32GB machine with me, and can test it here, too.

**Comment by molpopgen** [comment]
I could not replicate the OOM via the current `main` after changing the benchmark to look like this:

```py
        for impl in [
            # benchmark_pythran,
            # benchmark_numba,
            # benchmark_tskit,
            benchmark_c_sequential,
            # This is running out of memory on my machine.
            benchmark_cpp_sequential,
            # benchmark_biopython,
        ]:
```

**Comment by molpopgen** [comment]
Seems my failure to replicate was luck, not design, allocating just enough to stay under the radar.

**Comment by molpopgen** [comment]
The plot thickens @jeromekelleher.  It is the PRE-allocated version causing all the excess consumption, and not the heap-allocated version.  In other words, the one that runs faster is taking much more ram, and moving the operations into separate scopes via functions only improves the situation a small amount.

**Comment by molpopgen** [comment]
@jeromekelleher -- I believe this is fixed in #20.  This was a c++ "gotcha" that I should have caught.  Grrr....

**Comment by jeromekelleher** [comment]
Aha! I bet that was the cause of the weird timings you were seeing too.

**Comment by molpopgen** [comment]
> Aha! I bet that was the cause of the weird timings you were seeing too.

Doesn't seem to change it, actually.  That version was correct, as the unique pointer is move-only, so trying to code it wrong would hav not compiled.  It was only an issue with the stack-allocated version.

**Comment by jeromekelleher** [comment]
Huh, weird.

**Comment by molpopgen** [comment]
> Huh, weird.

Yeah.  It is, a bit.
